FIREFOX_LOCATION=${FIREFOX_LOCATION}
OPENAI_API_KEY=${OPENAI_API_KEY}
BROWSERLESS_API_KEY=${BROWSERLESS_API_KEY}
PINECONE_API_KEY=${PINECONE_API_KEY}
PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
SERPER_API_KEY=${SERPER_API_KEY}
LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}